services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE peep_manager_test;'
  - psql -d chitter_app_test -U postgres -f db/migrations/05_create_test_tables.sql

script:
  - bundle exec rspec
